---
# supported frameworks: mocha|jest|jasmine
framework: jest

preRun:
  # set of commands to run before running the tests like `yarn install`, `yarn build`
  command:
    - yarn

postMerge:
  pattern:
    - "/tests/.*-spec\\.ts?$"
  # strategy for trigerring builds for post-merge
  strategy:
    threshold: 1
    name: after_n_commits

preMerge:
  pattern:
    - "/tests/.*-spec\\.ts?$"

config: package.json

# configure whether to smartSelect test-cases. Default true
smartRun: true

# number of containers in which the tests must be splitted into for execution
parallelism: 1

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
version: 1.0.0
